apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: db-job
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: sikiryl/dbup
        name: db-job
        resources: {}
      restartPolicy: Never
status: {}
